In [1]:
import numpy as np

In [3]:
matrix = np.array([[2,3,1], [4,0,5]])

In [4]:
print(matrix)

[[2 3 1]
 [4 0 5]]


In [5]:
mb = np.array([[1,4], [2,3], [0,6]])

In [6]:
print(mb)

[[1 4]
 [2 3]
 [0 6]]


In [7]:
dp = np.dot(matrix, mb)

In [8]:
print(dp)

[[ 8 23]
 [ 4 46]]


In [9]:
q3m = np.array([[2,1],[0,5]])

In [10]:
eigenvalues, eigenvectors = np.linalg.eig(q3m)

In [11]:
print(eigenvalues)

[2. 5.]


In [12]:
def lu_decomposition(matrix):
    # Check whether the matrix is invertible
    if np.linalg.det(matrix) == 0:
        raise ValueError("Matrix is not invertible.")

    # Extract elements of the matrix
    a, b = matrix[0, :]
    c, d = matrix[1, :]

    # Calculate elements of L and U
    l11, l21, l22 = 1, c / a, 1
    u11, u12, u22 = a, b, d - (c * b) / a

    # Construct the L and U matrices
    L = np.array([[l11, 0], [l21, l22]])
    U = np.array([[u11, u12], [0, u22]])

    return L, U

In [13]:
q5m = np.array([[2,1], [8,7]])

In [14]:
print(q5m)

[[2 1]
 [8 7]]


In [15]:
q5l, q5u = lu_decomposition(q5m)

In [16]:
print(q5l)

[[1. 0.]
 [4. 1.]]


In [17]:
print(q5u)

[[2. 1.]
 [0. 3.]]
